import type { Proposal, DashboardStats } from "./types";

export const MOCK_PROPOSALS: Proposal[] = [
  {
    id: "p1",
    customer_name: "James & Linda Carter",
    customer_address: "8412 Westheimer Rd, Houston TX 77063",
    technician_name: "Mike Johnson",
    visit_date: "2026-03-14",
    system_type: "split",
    service_type: "replacement",
    system_size_tons: 3.5,
    stage: "proposal_sent",
    good_price: "[PRICE TBD]",
    better_price: "[PRICE TBD]",
    best_price: "[PRICE TBD]",
    pipeline_value: 9800,
    urgency: "soon",
    r22_flag: true,
    notes: "R-22 system, 17 years old. Customer wants to upgrade before summer.",
    created_at: "2026-03-14T10:00:00Z",
    updated_at: "2026-03-15T14:30:00Z",
  },
  {
    id: "p2",
    customer_name: "Roberto Vasquez",
    customer_address: "2200 Main St, Houston TX 77002",
    technician_name: "Dave Chen",
    visit_date: "2026-03-15",
    system_type: "heat_pump",
    service_type: "replacement",
    system_size_tons: 4.0,
    stage: "follow_up",
    good_price: "[PRICE TBD]",
    better_price: "[PRICE TBD]",
    best_price: "[PRICE TBD]",
    pipeline_value: 11200,
    urgency: "routine",
    r22_flag: false,
    notes: "Comparing with 2 other companies. Follow up Friday.",
    created_at: "2026-03-15T09:00:00Z",
    updated_at: "2026-03-16T11:00:00Z",
  },
  {
    id: "p3",
    customer_name: "Sarah Mitchell",
    customer_address: "501 Crawford St, Houston TX 77002",
    technician_name: "Mike Johnson",
    visit_date: "2026-03-16",
    system_type: "split",
    service_type: "replacement",
    system_size_tons: 2.5,
    stage: "won",
    good_price: "[PRICE TBD]",
    better_price: "[PRICE TBD]",
    best_price: "[PRICE TBD]",
    pipeline_value: 7400,
    urgency: "urgent",
    r22_flag: false,
    notes: "Signed on Better tier. Install scheduled for 3/20.",
    created_at: "2026-03-16T13:00:00Z",
    updated_at: "2026-03-17T08:00:00Z",
  },
  {
    id: "p4",
    customer_name: "Thompson Family",
    customer_address: "9800 Katy Fwy, Houston TX 77024",
    technician_name: "Dave Chen",
    visit_date: "2026-03-17",
    system_type: "package_unit",
    service_type: "replacement",
    system_size_tons: 5.0,
    stage: "estimate_ready",
    good_price: "[PRICE TBD]",
    better_price: "[PRICE TBD]",
    best_price: "[PRICE TBD]",
    pipeline_value: 14500,
    urgency: "routine",
    r22_flag: false,
    notes: "Large package unit, rooftop. Awaiting review before sending.",
    created_at: "2026-03-17T07:00:00Z",
    updated_at: "2026-03-17T07:00:00Z",
  },
  {
    id: "p5",
    customer_name: "Diana Nguyen",
    customer_address: "3300 Montrose Blvd, Houston TX 77006",
    technician_name: "Mike Johnson",
    visit_date: "2026-03-17",
    system_type: "mini_split",
    service_type: "new_install",
    system_size_tons: 1.5,
    stage: "new_lead",
    good_price: "[PRICE TBD]",
    better_price: "[PRICE TBD]",
    best_price: "[PRICE TBD]",
    pipeline_value: 4200,
    urgency: "routine",
    r22_flag: false,
    notes: "Garage conversion. Needs ductless mini-split.",
    created_at: "2026-03-17T09:30:00Z",
    updated_at: "2026-03-17T09:30:00Z",
  },
  {
    id: "p6",
    customer_name: "Marcus & Tanya Williams",
    customer_address: "6700 Bissonnet St, Houston TX 77074",
    technician_name: "Dave Chen",
    visit_date: "2026-03-13",
    system_type: "split",
    service_type: "replacement",
    system_size_tons: 3.0,
    stage: "lost",
    good_price: "[PRICE TBD]",
    better_price: "[PRICE TBD]",
    best_price: "[PRICE TBD]",
    pipeline_value: 8600,
    urgency: "soon",
    r22_flag: true,
    notes: "Went with a competitor. Price was the deciding factor.",
    created_at: "2026-03-13T14:00:00Z",
    updated_at: "2026-03-16T16:00:00Z",
  },
  {
    id: "p7",
    customer_name: "Kevin Patel",
    customer_address: "1500 Post Oak Blvd, Houston TX 77056",
    technician_name: "Mike Johnson",
    visit_date: "2026-03-17",
    system_type: "split",
    service_type: "replacement",
    system_size_tons: 4.0,
    stage: "appointment_set",
    good_price: "[PRICE TBD]",
    better_price: "[PRICE TBD]",
    best_price: "[PRICE TBD]",
    pipeline_value: 10800,
    urgency: "soon",
    r22_flag: false,
    notes: "Appointment confirmed for 3/19 at 10am.",
    created_at: "2026-03-17T11:00:00Z",
    updated_at: "2026-03-17T11:00:00Z",
  },
  {
    id: "p8",
    customer_name: "Hernandez Household",
    customer_address: "4400 Telephone Rd, Houston TX 77087",
    technician_name: "Dave Chen",
    visit_date: "2026-03-16",
    system_type: "heat_pump",
    service_type: "replacement",
    system_size_tons: 3.5,
    stage: "proposal_sent",
    good_price: "[PRICE TBD]",
    better_price: "[PRICE TBD]",
    best_price: "[PRICE TBD]",
    pipeline_value: 9200,
    urgency: "urgent",
    r22_flag: true,
    notes: "R-22 heat pump failure. No cooling — hot family. Sent proposal 3/16.",
    created_at: "2026-03-16T08:00:00Z",
    updated_at: "2026-03-16T17:00:00Z",
  },
];

export const MOCK_STATS: DashboardStats = {
  total_proposals_month: 12,
  pipeline_value: 98400,
  won_this_month: 3,
  win_rate: 42,
  avg_deal_size: 9200,
  urgent_count: 2,
  follow_up_count: 3,
  proposals_by_stage: {
    new_lead: 2,
    appointment_set: 2,
    estimate_ready: 1,
    proposal_sent: 3,
    follow_up: 2,
    won: 3,
    lost: 1,
  },
};
